[package]
name = "ganache_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
web3 = "0.17.0"
serde = { version = "1.0", features = ["derive"] }